spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.200.46.110:3306/DBtrip?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: zido
    password: tripones

  data:
    redis:
      host: 43.200.46.110
      port: 6379

  profiles:
    include: API-KEY

mybatis:
  mapper-locations: classpath:mappers/**.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-custom-ui.html
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json